export enum PRIVILEGE_NAME {
  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
  ORDER_MANAGEMENT = 'ORDER_MANAGEMENT',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  VENDOR_MANAGEMENT = 'VENDOR_MANAGEMENT',
  CATEGORY_MANAGEMENT = 'CATEGORY_MANAGEMENT',
  REVIEW_MANAGEMENT = 'REVIEW_MANAGEMENT',
  PAYMENT_MANAGEMENT = 'PAYMENT_MANAGEMENT',
  SHIPPING_MANAGEMENT = 'SHIPPING_MANAGEMENT',
  COUPON_MANAGEMENT = 'COUPON_MANAGEMENT',
  REPORT_MANAGEMENT = 'REPORT_MANAGEMENT',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  PRIVILEGE_MANAGEMENT = 'PRIVILEGE_MANAGEMENT',
}

export enum PRIVILEGE_SUBNAME {
  // Product Management
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  PRODUCT_APPROVE = 'PRODUCT_APPROVE',

  // Order Management
  ORDER_VIEW = 'ORDER_VIEW',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_REFUND = 'ORDER_REFUND',

  // User Management
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Vendor Management
  VENDOR_VIEW = 'VENDOR_VIEW',
  VENDOR_APPROVE = 'VENDOR_APPROVE',
  VENDOR_UPDATE = 'VENDOR_UPDATE',
  VENDOR_DELETE = 'VENDOR_DELETE',

  // Category Management
  CATEGORY_VIEW = 'CATEGORY_VIEW',
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_UPDATE = 'CATEGORY_UPDATE',
  CATEGORY_DELETE = 'CATEGORY_DELETE',

  // Review Management
  REVIEW_VIEW = 'REVIEW_VIEW',
  REVIEW_APPROVE = 'REVIEW_APPROVE',
  REVIEW_DELETE = 'REVIEW_DELETE',

  // Payment Management
  PAYMENT_VIEW = 'PAYMENT_VIEW',
  PAYMENT_REFUND = 'PAYMENT_REFUND',

  // Shipping Management
  SHIPPING_VIEW = 'SHIPPING_VIEW',
  SHIPPING_UPDATE = 'SHIPPING_UPDATE',

  // Coupon Management
  COUPON_VIEW = 'COUPON_VIEW',
  COUPON_CREATE = 'COUPON_CREATE',
  COUPON_UPDATE = 'COUPON_UPDATE',
  COUPON_DELETE = 'COUPON_DELETE',

  // ROLE Management
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // PRIVILEGE Management
  PRIVILEGE_VIEW = 'PRIVILEGE_VIEW',
  PRIVILEGE_CREATE = 'PRIVILEGE_CREATE',
  PRIVILEGE_UPDATE = 'PRIVILEGE_UPDATE',
  PRIVILEGE_DELETE = 'PRIVILEGE_DELETE',

  // Report Management
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
}

export const PRIVILEGE_GROUP = {
  PRODUCT_MANAGEMENT: {
    PRODUCT_VIEW: PRIVILEGE_SUBNAME.PRODUCT_VIEW,
    PRODUCT_CREATE: PRIVILEGE_SUBNAME.PRODUCT_CREATE,
    PRODUCT_UPDATE: PRIVILEGE_SUBNAME.PRODUCT_UPDATE,
    PRODUCT_DELETE: PRIVILEGE_SUBNAME.PRODUCT_DELETE,
    PRODUCT_APPROVE: PRIVILEGE_SUBNAME.PRODUCT_APPROVE,
  },
  ORDER_MANAGEMENT: {
    ORDER_VIEW: PRIVILEGE_SUBNAME.ORDER_VIEW,
    ORDER_UPDATE: PRIVILEGE_SUBNAME.ORDER_UPDATE,
    ORDER_CANCEL: PRIVILEGE_SUBNAME.ORDER_CANCEL,
    ORDER_REFUND: PRIVILEGE_SUBNAME.ORDER_REFUND,
  },
  USER_MANAGEMENT: {
    USER_VIEW: PRIVILEGE_SUBNAME.USER_VIEW,
    USER_CREATE: PRIVILEGE_SUBNAME.USER_CREATE,
    USER_UPDATE: PRIVILEGE_SUBNAME.USER_UPDATE,
    USER_DELETE: PRIVILEGE_SUBNAME.USER_DELETE,
  },
  VENDOR_MANAGEMENT: {
    VENDOR_VIEW: PRIVILEGE_SUBNAME.VENDOR_VIEW,
    VENDOR_APPROVE: PRIVILEGE_SUBNAME.VENDOR_APPROVE,
    VENDOR_UPDATE: PRIVILEGE_SUBNAME.VENDOR_UPDATE,
    VENDOR_DELETE: PRIVILEGE_SUBNAME.VENDOR_DELETE,
  },
  CATEGORY_MANAGEMENT: {
    CATEGORY_VIEW: PRIVILEGE_SUBNAME.CATEGORY_VIEW,
    CATEGORY_CREATE: PRIVILEGE_SUBNAME.CATEGORY_CREATE,
    CATEGORY_UPDATE: PRIVILEGE_SUBNAME.CATEGORY_UPDATE,
    CATEGORY_DELETE: PRIVILEGE_SUBNAME.CATEGORY_DELETE,
  },
  REVIEW_MANAGEMENT: {
    REVIEW_VIEW: PRIVILEGE_SUBNAME.REVIEW_VIEW,
    REVIEW_APPROVE: PRIVILEGE_SUBNAME.REVIEW_APPROVE,
    REVIEW_DELETE: PRIVILEGE_SUBNAME.REVIEW_DELETE,
  },
  PAYMENT_MANAGEMENT: {
    PAYMENT_VIEW: PRIVILEGE_SUBNAME.PAYMENT_VIEW,
    PAYMENT_REFUND: PRIVILEGE_SUBNAME.PAYMENT_REFUND,
  },
  SHIPPING_MANAGEMENT: {
    SHIPPING_VIEW: PRIVILEGE_SUBNAME.SHIPPING_VIEW,
    SHIPPING_UPDATE: PRIVILEGE_SUBNAME.SHIPPING_UPDATE,
  },
  COUPON_MANAGEMENT: {
    COUPON_VIEW: PRIVILEGE_SUBNAME.COUPON_VIEW,
    COUPON_CREATE: PRIVILEGE_SUBNAME.COUPON_CREATE,
    COUPON_UPDATE: PRIVILEGE_SUBNAME.COUPON_UPDATE,
    COUPON_DELETE: PRIVILEGE_SUBNAME.COUPON_DELETE,
  },
  ROLE_MANAGEMENT: {
    ROLE_VIEW: PRIVILEGE_SUBNAME.ROLE_VIEW,
    ROLE_CREATE: PRIVILEGE_SUBNAME.ROLE_CREATE,
    ROLE_UPDATE: PRIVILEGE_SUBNAME.ROLE_UPDATE,
    ROLE_DELETE: PRIVILEGE_SUBNAME.ROLE_DELETE,
  },
  PRIVILEGE_MANAGEMENT: {
    PRIVILEGE_VIEW: PRIVILEGE_SUBNAME.PRIVILEGE_VIEW,
    PRIVILEGE_CREATE: PRIVILEGE_SUBNAME.PRIVILEGE_CREATE,
    PRIVILEGE_UPDATE: PRIVILEGE_SUBNAME.PRIVILEGE_UPDATE,
    PRIVILEGE_DELETE: PRIVILEGE_SUBNAME.PRIVILEGE_DELETE,
  },
  REPORT_MANAGEMENT: {
    REPORT_VIEW: PRIVILEGE_SUBNAME.REPORT_VIEW,
    REPORT_EXPORT: PRIVILEGE_SUBNAME.REPORT_EXPORT,
  },
} as const;
